'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.6.1055.0.
'

Namespace MysteryDungeon.Explorers.PPMDU

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=True)>
    Partial Public Class MoveID

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
    Partial Public Class Pokemon

        Private stringsField() As PokemonStrings

        Private genderedEntityField() As PokemonGenderedEntity

        Private movesetField() As PokemonMoveset

        Private statsGrowthField() As PokemonStatsGrowthLevel

        Private gameVersionField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Strings", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Strings() As PokemonStrings()
            Get
                Return Me.stringsField
            End Get
            Set
                Me.stringsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("GenderedEntity", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property GenderedEntity() As PokemonGenderedEntity()
            Get
                Return Me.genderedEntityField
            End Get
            Set
                Me.genderedEntityField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Moveset", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Moveset() As PokemonMoveset()
            Get
                Return Me.movesetField
            End Get
            Set
                Me.movesetField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),
     System.Xml.Serialization.XmlArrayItemAttribute("Level", GetType(PokemonStatsGrowthLevel), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=False)>
        Public Property StatsGrowth() As PokemonStatsGrowthLevel()
            Get
                Return Me.statsGrowthField
            End Get
            Set
                Me.statsGrowthField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property gameVersion() As String
            Get
                Return Me.gameVersionField
            End Get
            Set
                Me.gameVersionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonStrings

        Private englishField() As PokemonStringsEnglish

        Private frenchField() As PokemonStringsFrench

        Private germanField() As PokemonStringsGerman

        Private italianField() As PokemonStringsItalian

        Private spanishField() As PokemonStringsSpanish

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("English", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property English() As PokemonStringsEnglish()
            Get
                Return Me.englishField
            End Get
            Set
                Me.englishField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("French", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property French() As PokemonStringsFrench()
            Get
                Return Me.frenchField
            End Get
            Set
                Me.frenchField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("German", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property German() As PokemonStringsGerman()
            Get
                Return Me.germanField
            End Get
            Set
                Me.germanField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Italian", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Italian() As PokemonStringsItalian()
            Get
                Return Me.italianField
            End Get
            Set
                Me.italianField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Spanish", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Spanish() As PokemonStringsSpanish()
            Get
                Return Me.spanishField
            End Get
            Set
                Me.spanishField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonStringsEnglish

        Private nameField As String

        Private categoryField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Category() As String
            Get
                Return Me.categoryField
            End Get
            Set
                Me.categoryField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonStringsFrench

        Private nameField As String

        Private categoryField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Category() As String
            Get
                Return Me.categoryField
            End Get
            Set
                Me.categoryField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonStringsGerman

        Private nameField As String

        Private categoryField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Category() As String
            Get
                Return Me.categoryField
            End Get
            Set
                Me.categoryField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonStringsItalian

        Private nameField As String

        Private categoryField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Category() As String
            Get
                Return Me.categoryField
            End Get
            Set
                Me.categoryField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonStringsSpanish

        Private nameField As String

        Private categoryField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Category() As String
            Get
                Return Me.categoryField
            End Get
            Set
                Me.categoryField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonGenderedEntity

        Private pokeIDField As String

        Private unk31Field As String

        Private pokedexNumberField As String

        Private unk1Field As String

        Private spriteIndexField As String

        Private genderField As String

        Private bodySizeField As String

        Private primaryTypeField As String

        Private secondaryTypeField As String

        Private movementTypeField As String

        Private iQGroupField As String

        Private primaryAbilityField As String

        Private secondaryAbilityField As String

        Private bitfieldField As String

        Private expYieldField As String

        Private recruitRate1Field As String

        Private recruitRate2Field As String

        Private weightField As String

        Private sizeField As String

        Private unk17Field As String

        Private unk18Field As String

        Private unk19Field As String

        Private unk20Field As String

        Private unk21Field As String

        Private basePokemonIndexField As String

        Private unk27Field As String

        Private unk28Field As String

        Private unk29Field As String

        Private unk30Field As String

        Private evolutionReqField() As PokemonGenderedEntityEvolutionReq

        Private baseStatsField() As PokemonGenderedEntityBaseStats

        Private exclusiveItemsField() As PokemonGenderedEntityExclusiveItemsItemID

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property PokeID() As String
            Get
                Return Me.pokeIDField
            End Get
            Set
                Me.pokeIDField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Unk31() As String
            Get
                Return Me.unk31Field
            End Get
            Set
                Me.unk31Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property PokedexNumber() As String
            Get
                Return Me.pokedexNumberField
            End Get
            Set
                Me.pokedexNumberField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Unk1() As String
            Get
                Return Me.unk1Field
            End Get
            Set
                Me.unk1Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property SpriteIndex() As String
            Get
                Return Me.spriteIndexField
            End Get
            Set
                Me.spriteIndexField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Gender() As String
            Get
                Return Me.genderField
            End Get
            Set
                Me.genderField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property BodySize() As String
            Get
                Return Me.bodySizeField
            End Get
            Set
                Me.bodySizeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property PrimaryType() As String
            Get
                Return Me.primaryTypeField
            End Get
            Set
                Me.primaryTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property SecondaryType() As String
            Get
                Return Me.secondaryTypeField
            End Get
            Set
                Me.secondaryTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property MovementType() As String
            Get
                Return Me.movementTypeField
            End Get
            Set
                Me.movementTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IQGroup() As String
            Get
                Return Me.iQGroupField
            End Get
            Set
                Me.iQGroupField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property PrimaryAbility() As String
            Get
                Return Me.primaryAbilityField
            End Get
            Set
                Me.primaryAbilityField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property SecondaryAbility() As String
            Get
                Return Me.secondaryAbilityField
            End Get
            Set
                Me.secondaryAbilityField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Bitfield() As String
            Get
                Return Me.bitfieldField
            End Get
            Set
                Me.bitfieldField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property ExpYield() As String
            Get
                Return Me.expYieldField
            End Get
            Set
                Me.expYieldField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property RecruitRate1() As String
            Get
                Return Me.recruitRate1Field
            End Get
            Set
                Me.recruitRate1Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property RecruitRate2() As String
            Get
                Return Me.recruitRate2Field
            End Get
            Set
                Me.recruitRate2Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Weight() As String
            Get
                Return Me.weightField
            End Get
            Set
                Me.weightField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Size() As String
            Get
                Return Me.sizeField
            End Get
            Set
                Me.sizeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Unk17() As String
            Get
                Return Me.unk17Field
            End Get
            Set
                Me.unk17Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Unk18() As String
            Get
                Return Me.unk18Field
            End Get
            Set
                Me.unk18Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Unk19() As String
            Get
                Return Me.unk19Field
            End Get
            Set
                Me.unk19Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Unk20() As String
            Get
                Return Me.unk20Field
            End Get
            Set
                Me.unk20Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Unk21() As String
            Get
                Return Me.unk21Field
            End Get
            Set
                Me.unk21Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property BasePokemonIndex() As String
            Get
                Return Me.basePokemonIndexField
            End Get
            Set
                Me.basePokemonIndexField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Unk27() As String
            Get
                Return Me.unk27Field
            End Get
            Set
                Me.unk27Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Unk28() As String
            Get
                Return Me.unk28Field
            End Get
            Set
                Me.unk28Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Unk29() As String
            Get
                Return Me.unk29Field
            End Get
            Set
                Me.unk29Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Unk30() As String
            Get
                Return Me.unk30Field
            End Get
            Set
                Me.unk30Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("EvolutionReq", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property EvolutionReq() As PokemonGenderedEntityEvolutionReq()
            Get
                Return Me.evolutionReqField
            End Get
            Set
                Me.evolutionReqField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("BaseStats", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property BaseStats() As PokemonGenderedEntityBaseStats()
            Get
                Return Me.baseStatsField
            End Get
            Set
                Me.baseStatsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),
     System.Xml.Serialization.XmlArrayItemAttribute("ItemID", GetType(PokemonGenderedEntityExclusiveItemsItemID), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property ExclusiveItems() As PokemonGenderedEntityExclusiveItemsItemID()
            Get
                Return Me.exclusiveItemsField
            End Get
            Set
                Me.exclusiveItemsField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonGenderedEntityEvolutionReq

        Private preEvoIndexField As String

        Private methodField As String

        Private param1Field As String

        Private param2Field As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property PreEvoIndex() As String
            Get
                Return Me.preEvoIndexField
            End Get
            Set
                Me.preEvoIndexField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Method() As String
            Get
                Return Me.methodField
            End Get
            Set
                Me.methodField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Param1() As String
            Get
                Return Me.param1Field
            End Get
            Set
                Me.param1Field = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Param2() As String
            Get
                Return Me.param2Field
            End Get
            Set
                Me.param2Field = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonGenderedEntityBaseStats

        Private hpField As String

        Private attackField As String

        Private spAttackField As String

        Private defenseField As String

        Private spDefenseField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property HP() As String
            Get
                Return Me.hpField
            End Get
            Set
                Me.hpField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Attack() As String
            Get
                Return Me.attackField
            End Get
            Set
                Me.attackField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property SpAttack() As String
            Get
                Return Me.spAttackField
            End Get
            Set
                Me.spAttackField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Defense() As String
            Get
                Return Me.defenseField
            End Get
            Set
                Me.defenseField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property SpDefense() As String
            Get
                Return Me.spDefenseField
            End Get
            Set
                Me.spDefenseField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonGenderedEntityExclusiveItemsItemID

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonMoveset

        Private levelUpMovesField() As PokemonMovesetLevelUpMovesLearn

        Private eggMovesField() As MoveID

        Private hmTmMovesField() As MoveID

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),
     System.Xml.Serialization.XmlArrayItemAttribute("Learn", GetType(PokemonMovesetLevelUpMovesLearn), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=False)>
        Public Property LevelUpMoves() As PokemonMovesetLevelUpMovesLearn()
            Get
                Return Me.levelUpMovesField
            End Get
            Set
                Me.levelUpMovesField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),
     System.Xml.Serialization.XmlArrayItemAttribute("MoveID", GetType(MoveID))>
        Public Property EggMoves() As MoveID()
            Get
                Return Me.eggMovesField
            End Get
            Set
                Me.eggMovesField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),
     System.Xml.Serialization.XmlArrayItemAttribute("MoveID", GetType(MoveID))>
        Public Property HmTmMoves() As MoveID()
            Get
                Return Me.hmTmMovesField
            End Get
            Set
                Me.hmTmMovesField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonMovesetLevelUpMovesLearn

        Private levelField As String

        Private moveIDField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Level() As String
            Get
                Return Me.levelField
            End Get
            Set
                Me.levelField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property MoveID() As String
            Get
                Return Me.moveIDField
            End Get
            Set
                Me.moveIDField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class PokemonStatsGrowthLevel

        Private requiredExpField As String

        Private hpField As String

        Private attackField As String

        Private spAttackField As String

        Private defenseField As String

        Private spDefenseField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property RequiredExp() As String
            Get
                Return Me.requiredExpField
            End Get
            Set
                Me.requiredExpField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property HP() As String
            Get
                Return Me.hpField
            End Get
            Set
                Me.hpField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Attack() As String
            Get
                Return Me.attackField
            End Get
            Set
                Me.attackField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property SpAttack() As String
            Get
                Return Me.spAttackField
            End Get
            Set
                Me.spAttackField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Defense() As String
            Get
                Return Me.defenseField
            End Get
            Set
                Me.defenseField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property SpDefense() As String
            Get
                Return Me.spDefenseField
            End Get
            Set
                Me.spDefenseField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
    Partial Public Class NewDataSet

        Private itemsField() As Object

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("MoveID", GetType(MoveID), IsNullable:=True),
     System.Xml.Serialization.XmlElementAttribute("Pokemon", GetType(Pokemon))>
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
    End Class
End Namespace