'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SkyEditor.ROMEditor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -718398628
        '''-435230016
        '''-1654573358
        '''1903015878
        '''503435898
        '''-1410980566
        '''989233605
        '''1935809866
        '''-179177891
        '''1246365421
        '''-92254823
        '''1628463885
        '''-97659969
        '''257607992
        '''-1524198606
        '''-677644957
        '''-1992013654
        '''-384388233
        '''115663861
        '''-168484640
        '''868012407
        '''259992450
        '''2119179250
        '''730694348
        '''-1340880491
        '''603494511
        '''1136534868
        '''834898904
        '''-1018186886
        '''724043848
        '''-416731511
        '''-410355533
        '''-477930037
        '''-1457571583
        '''59851618
        '''1445443351
        '''1473822057
        '''1729223756
        '''911239694
        '''-1231703692
        '''-1394792168
        '''-1543689364
        '''1997354599
        '''- [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property PSMD_Move_Name_Hashes() As String
            Get
                Return ResourceManager.GetString("PSMD_Move_Name_Hashes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 150118018
        '''781321446
        '''-1427025407
        '''-901415510
        '''-523595615
        '''663067603
        '''-487879711
        '''-478740406
        '''-93572853
        '''2023463552
        '''-157611292
        '''-789800013
        '''-75220958
        '''-245035771
        '''-376462679
        '''-1156314694
        '''974848216
        '''643055585
        '''300582488
        '''1393501584
        '''642546530
        '''-137557997
        '''-1911925550
        '''-939516080
        '''-598384997
        '''1896924932
        '''143739870
        '''1400696415
        '''-1822701762
        '''1367585910
        '''-793621678
        '''1259679618
        '''-67159027
        '''188205218
        '''1647527314
        '''607124172
        '''-389869207
        '''-55547876
        '''-148158505
        '''1146254177
        '''-1019573359
        '''-3862091
        '''797602173
        '''-2063448 [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property PSMD_Pokemon_Name_Hashes() As String
            Get
                Return ResourceManager.GetString("PSMD_Pokemon_Name_Hashes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public Shared ReadOnly Property unluac() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("unluac", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Class
End Namespace
